global:
    scrape_interval: 5s
    evaluation_interval: 15s
#    external_labels:
#        monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['airflow-prometheus:9090']

  - job_name: airflow
    scheme: http
    metrics_path: metrics
    static_configs:
      - targets: ['host.docker.internal:9102']
        labels:
          airflow_id: 'airflow'
  
    tls_config:
      insecure_skip_verify: true
