apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: airflow
    type: prometheus
    access: direct
    url: http://localhost:9092
